// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuepkorqdnabfxtynytf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZXBrb3JxZG5hYmZ4dHlueXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzgyNTIsImV4cCI6MjA4ODU1NDI1Mn0.z8AdcXBjFLAYkS0cs-AZKXYQw3I019DdK4VvyKUIhKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});